version: '3'

services:
  #
  # Project reverse proxy
  nginx-proxy:
    image: ${COMPOSE_PROJECT_NAME}_proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    restart: unless-stopped
    expose:
      - "80"
    build:
      context: ./data/nginx-proxy
    environment:
      - DHPARAM_GENERATION=false
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=hub.ensg-sdi.docker
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      elabs-revproxy:
        ipv4_address: 172.24.0.3

  #
  # dnsmasq config for containers
  dns-gen:
    build: ./data/dns-gen
    container_name: ${COMPOSE_PROJECT_NAME}_dns-gen
    restart: unless-stopped
    expose:
      - "53:53/udp"
    depends_on:
      - nginx-proxy
    logging:
      options:
        max-size: "10m"
    volumes:
      - dns-gen-config:/etc/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      elabs-revproxy:
        ipv4_address: 172.24.0.2 

  #
  # Portainer docker admin GUI
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      elabs-revproxy:
        ipv4_address: 172.24.0.4

volumes:
  vhost.d:
  portainer-data:
  dns-gen-config:

networks:
  elabs-revproxy:
    name: ${APPS_NETWORK}
    external: true
    ipam:
      config:
        - subnet: "172.24.0.0/16"
